### ISSUE TITLE
When filename is getting Big then tippy is getting overflowed out of tooltip container

### ISSUE THREAD

**Issue by awesome-yasin** [farengeyt451/ngx-tippy-wrapper#55]

**Comment by farengeyt451** [comment]
@awesome-yasin Provide more details or recreate the issue in another repo.

**Comment by awesome-yasin** [comment]
@farengeyt451 If you see when i hover this foldername and its very large name so text is getting overflowed 
![image](https://github.com/farengeyt451/ngx-tippy-wrapper/assets/85479838/97a5068e-ec6a-4bd5-aca3-bc97fa684a38)

**Comment by awesome-yasin** [comment]
I used simple [ngxTippy]=filename in my html div

**Comment by farengeyt451** [comment]
@awesome-yasin I am not sure about adding a built-in cut text feature. 
You can use CSS fix for this:

```html
    <button
      [ngxTippy]="filename"
      tippyClassName="cut-text-overflow"
      [tippyProps]="{
        ...
      }"
    >
      Button
    </button>
```

```css
  .cut-text-overflow {
    .tippy-content {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }
  }
```

<img width="371" alt="image" src="https://github.com/farengeyt451/ngx-tippy-wrapper/assets/13274254/67437edd-2717-4ace-beb6-9e74347e0c7c">
